version: "3"

services:
  postgres:
    image: postgres:12.2
    container_name: postgres-database
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: secret_pass
        POSTGRES_DB: workflow_db

  rabbitmq-server:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq-server
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge